### ISSUE TITLE
How to download stable release version?

### ISSUE THREAD

**Issue by Matgen84** [n-d-k/OpenCorePkg#11]
Hi
Thanks for your great job 

I can't download n-d-k stable 0.5.4.

Please help me

**Comment by n-d-k** [comment]
Hi,
Since I don't release any binary to download, The stable release version on this fork is just a snap shot of the source code before it started a new version. Unlike Clover, OC has many individual components and they do move functions around from one component to others, which make it hard to keep track all of them.  OC main components are OpenCorePkg, and OcSupportPkg, and some other support packages which doesn't change much and doesn't affect if it's changed.  OpenCore is pretty much stable all across, you can just compile the most recent one. Any change to the source code are much pretty much tested by OC team and I do test it again before pushing it to repo.

**Comment by Matgen84** [comment]
Hi

Ok. I compile n-d-k OC 0.5.4 from your stable source. If I understand well.
Thanks
