### ISSUE TITLE
Windows is always default Boot Device in New Version with Icon Support

### ISSUE THREAD

**Issue by karacho-ak** [n-d-k/OpenCorePkg#15]
Nice Work n-d-k.
To me it turns out now, that Windows is always the default boot device, even with selected macOS in System Preferences->Startup Disk. I have set Windows in Misc->Entries->Hidden to YES, but the Windows Icon appears anyway. With the previous version (without Icons) it worked like expected. I just got the two macOS disks and the whole rest (Windows, Recoverys, Shell and Reset Nvram) appeared only after pressing the space key.  Do you have any Suggestions?

**Comment by n-d-k** [comment]
If in your config.plist, you have AllowSetDefault ON, then you can use Ctrl + Index number or Ctrl + Enter on selected entry to set the always default to that entry.  To use the auto boot to last booted os , you need to have this option to OFF.

By default, all hidden custom entries, recovery, tools and reset Nvram will not show up until pressing spacebar, it's how it work in previous text boot picker and in this new UI boot picker as well.  There wasn't anything change beside rendering list of icons instead of list of text entries.

**Comment by karacho-ak** [comment]
Oh, i see. Thank you for answering. I was able to fix my Problem by doing Nvram Reset. I guess it was my fault, because i'm playing around with bcfg earlier. I Apologize for my dumb.
