### ISSUE TITLE
ACPI->Quirks->EnableForAll ignores os listed in entries

### ISSUE THREAD

**Issue by steve3d** [n-d-k/OpenCorePkg#17]
my computer has a 1T ssd, so I installed the mac and windows both on this ssd, and I really don't know how to create two esp on one ssd and make each os use only one of these `esp`s. So I only have one esp on ssd.

So opencore can not detect windows on same esp, I have to use custom entries to add a windows boot option.

then here comes the problem, I have enabled the `Hyper-V` on windows 10, then no matter `EnableForAll` is true or false, windows 10 will always boot into BSOD, if I use F12 to boot windows at bios, then everything is fine.

so either `EnableForAll` doesn't work for entries or opencore has something conflict with `Hyper-V`  feature.

and another thing, seems you forgot to tag the 0.5.5 version.

**Comment by n-d-k** [comment]
Since you mention it, I was curious if that's the case,  and I went ahead and turned on my hyper-v on my windows 10 pro as it wasn't on before, I have no use for it.  After All Hyper-V option is checked and installed Windows 10 reboot just fine regardless of EnabledForAll on or off. And my win and mac are using the same drive.

fyi, only 1 EFI partition is allowed per drive and EnableForAll is just a switch on/off for OC to apply the ACPI patches that users listed in config.plist.

![screen_shot](https://user-images.githubusercontent.com/55958134/74097213-2bb21c00-4acf-11ea-9c5d-c547201a0aac.png)

**Comment by steve3d** [comment]
[oc.zip](https://github.com/n-d-k/OpenCorePkg/files/4176569/oc.zip)


here is my config, is there any wrong?

the only way for me to boot into windows is by add an item under 'Misc > Entries'

**Comment by steve3d** [comment]
and I did some more test, once I enabled `Hyper-V`, then opencore won't boot into windows, remove this feature, then everything works.

and one more thing, the latest version, now have gui picker, and the latest version can have proper 4k resolution on my monitor, but the first time the picker seems a little blurry, and if I enter the UEFIShell, the text are properly scale by 2, that's fine, then exit the shell, the graphical picker back to 100% scale, and no blurry.

**Comment by n-d-k** [comment]
Ya, for 4k monitor, it's auto scaled the icons to make them look proportionated to the screen, the downsize is, it will kinda look blurry up close. So it's either not scaling for 4k and icons will look kinda small or blurry.   I am not sure what people would prefer.  What do you prefer?

I may have to add some code to return the screen to original scaling state, since clearly the shell is kinda messed up the screen resolution. Thanks for pointing out the problem.

**Comment by steve3d** [comment]
there is `UEFI->Output->Scale` parameter, you can just stick to this setting to scale the icon and text, I'm sure anyone using this parameter other than 100% scale will choose the best value.

so if they choose the wrong value like something 145%, then the blurry text and icon are their fault, not your auto scale.

on an 4k monitor, the best should always be the 200 scale, which is `pixel perfect` scale,  and current auto scale clearly not set to 200 scale, more like 19x, close, but result is ugly blurry  text and icon.

**Comment by steve3d** [comment]
one more thing, the shell did not mess up the resolution, when `UEFI->Output->Scale` are set to 200, then the uefi shell are perfectly scaled to 200%, and every character are so perfect size and no blurry at all.

**Comment by n-d-k** [comment]
For the icons, unless using 256x256 pixel icons for 4k, the 128x128 pixels scale up to 200% will look jaggy on the edge and it looks kinda too big for small 4k monitor. Currently, it look proportionate with the screen at 175%  scale ratio on 4k monitor. Unless everyone with 4k monitor can grab a 256px icons to replace the 128px one, or not scaling at all for 4k, it will look small like Clover UI, it's not scaling at all for 4k.

**Comment by steve3d** [comment]
well, I thought the `icns` is just a container like the `ico` file format under windows,  I thought this icon format can have multiple resolution.

but the 175% scale really looks bad, both icon and text, clover has a svg based theme `Clovy`, which can be scale to any resolution.

and I don't think 200% scale will look two big on 4k monitor,  on any 4k monitor, 256x256 pixels will look exact same size on 1080p monitor of 128x128 pixels.

**Comment by steve3d** [comment]
please, leave that choice to users, and respect the `UEFI->Output->Scale` setting, if someone thought the 200% scale is too big, then he/she will change this to 175, and get a smaller icon and burry text. for me , I want the perfect 200% scale, and of course I want to set this by me, not by the `auto scale` algorithm which I can not control.

PS. why bother add more code that can not controlled by users, while there is some simple solution which can be controlled by users?

**Comment by n-d-k** [comment]
Sure, I'll make use of that setting and remove the auto scale mechanism, That setting was recently introduced after GUI boot picker was created.  Still haven't found time to look into those recent changes from OC thoroughly. But things will be changed for the better.
