### ISSUE TITLE
about resetnvram

### ISSUE THREAD

**Issue by btwise** [n-d-k/OpenCorePkg#2]
The allow resetnvram option is already enabled in config.plist, and the same config file can be displayed using the original OC, but not with your modified version, and the option to use the keyboard up and down in the startup menu can only be cycled through the first three options, and can not choose after the fourth item, why?

**Comment by n-d-k** [comment]
Please check your custom entries make sure everthing is shown in picker menu while it's not in hidden mode. And test the arrow key up/down while it's not in hidden mode.

The problem you experience with missing the reset nvram was probably the same problem with arrow key not cycle through the last entry. You may have some invalid entry that caused this. That's why i ask you to check your custom entries if you have any.  And if everything checkout fine with your custom entries, then your system must have an invalid entry which was detected by scanner but didn't get excluded from the total count.

**Comment by btwise** [comment]
I didn't add anything to the custom entry, I just used OC to automatically scan the displayed menu. Do I have to use custom entry to make the startup menu display perfectly? And now press the space bar appears recovery partition entry display is not complete, can not select operations, press the space bar again can not hide the recovery partition entry display is not complete!

**Comment by n-d-k** [comment]
No, you don't have to use custom entry,  try disable AllowNvramReset, and make sure no tool was enabled. Just entries from system, if one entry is messing up, the whole menu is out synced. So try to trace the step.

**Comment by btwise** [comment]
I've been through the system, and I'm at Config.plist file does not contain hide keys from custom projects, plus the space bar to display the resetNVRAM menu as the partition is restored, but using the up and down keys to select the loop is not friendly, it is recommended to redraw the start menu rendering mode instead of the pure console style!

**Comment by n-d-k** [comment]
The hidden keys are addition that this fork added, you have to create it yourself if you don't have that in your config.plist.  And Up/Down keys are much better than no up/down, and very friendly to me where one don't have to look for a number to press, you can still use the number selection if you don't want to use up/down.

That start menu is an optional menu, no need to invest time and resource to it when you can just use hotkeys to switch between your OSes without seeing that menu.  Just set show picker to off and use holding down w or x at boot to switch between Windows or OSX, and if you ever need to see that menu, just hold down option key at boot.  Even a nice ui menu like clover can't beat the Hotkeys switching, fast and effective. no need to see boot menu and choose, that's how it should work.

**Comment by btwise** [comment]
I see
