### ISSUE TITLE
question

### ISSUE THREAD

**Issue by btwise** [n-d-k/OpenCorePkg#3]
There are several questions I would like to ask:
1. I tried to use OC to boot my laptop. It was HP-840G3. It turned out to be 10.14.6 with CLOVER boot. Everything is normal. However, using OC boot, I found only another Windows partition in the boot menu instead of showing the existing one NVME MAC system partition. This is the reason for scanning. The scanning policy value in the configuration file is already 0.
2. I guided your version on my laptop, and unexpectedly found that the startup interface has a LOGO character and a version number on the lower right corner, but it cannot be displayed on my desktop computer
THANK YOU!

**Comment by n-d-k** [comment]
1.  I barely understand the first question.
2. Are you using the same version of OC?

**Comment by btwise** [comment]
My Laptop, which is currently CLOVER booting, works fine, but I switched to OC booting, and I couldn't find a bootable MACOS partition in the boot menu, I started OC booting with USB, and my MACOS partition is the NVME hard drive

**Comment by n-d-k** [comment]
Let me say this, switching from Clover to OC is no easy task, it took me a lots of reading, trial and error testing to figure out what's diiferent between Clover and OC setting, and my computer reset button is worn out because of it :( , unless you have the need to switch, just stick to whatever it worked. OC is not for everyone.
