### ISSUE TITLE
is it possible to sync the version to original repo and provide compiled version

### ISSUE THREAD

**Issue by steve3d** [n-d-k/OpenCorePkg#4]
these added feature is wonderful, but seems if I want to use it, the only way is compile this by myself,

so is there any possible to sync version to original repo, and also provide a compiled package?

thank you.

**Comment by n-d-k** [comment]
This fork is synced with original and will stay update to date with any changes from original repo. You can still sync it yourself with original repo as long as there's not conflict during merge. If there's conflict during the merge then it's better that I will be the one resolving it., because I know what's different between the two repos.

As for compiled package, I do not have any intention to release compiled package at the moment. New hackintosh users are better stick with one that has more supports.  This fork is intended for experienced users who already had their hack working properly.
