### ISSUE TITLE
How to get the PCI path of the BOOT partition?

### ISSUE THREAD

**Issue by btwise** [n-d-k/OpenCorePkg#6]
When add system boot parameters to a custom entry, how to get the full PCI path address of the BOOT partition?

**Comment by btwise** [comment]
Can you add a hotkey to the start menu to save the list of information you need on disk?

**Comment by n-d-k** [comment]
> When add system boot parameters to a custom entry, how to get the full PCI path address of the BOOT partition?

You need to use the debug version, which located in OpenCorePkg/edk2/Build/OpenCorePkg/DEBUG_XCODE5/X64/OpenCore-0.5.4-DEBUG.zip and set Misc->Debug->Target to 67.  It will save the bootlog to disk, In the log, look for anything with Dp, it's a potential DevicePath to entry.

About the key to copy entries info to disk, I already thought of that, but haven't got time to get to it. Since using the above method will achieve the same thing, still not sure if it's really needed.

**Comment by btwise** [comment]
This function is necessary!
Using the DEBUG function can find this path, but it seems too cumbersome for ordinary users, so a more convenient and quick way is the best!
The cause of the problem was a user, his MAC and Windows were installed on the same disk, but the Windows information could not be found in the boot menu to enter the Windows system correctly!
In the CLOVER boot menu, you can easily see the PCI path information of each bootable partition by pressing the space bar. It is also necessary to add this function to OC!
![screenshot2](https://user-images.githubusercontent.com/38809560/71705346-387d8900-2e1a-11ea-8e23-d42150d89acd.png)

**Comment by btwise** [comment]
Make a hotkey function, use the hotkey to automatically save all bootable PCI path information in a file under the EFI partition！

Or press the hotkey to automatically scan boot partitions available path to config.plist-->MISC, and set it to the disabled state to make it easier for the user to enable it

**Comment by n-d-k** [comment]
I will not work on this due to time constraint.
